// Endpoints are relative paths - axios client.ts will prepend baseURL
export const endpoints = {
  models: {
    status: 'models/status',
    detail: (name: string) => `models/${name}`,
  },
  query: {
    execute: 'query',
    history: 'query/history',
    byId: (id: string) => `query/${id}`,
  },
  metrics: {
    system: 'metrics/system',
    models: 'metrics/models',
  },
  settings: {
    get: 'settings',
    update: 'settings',
    reset: 'settings/reset',
    schema: 'settings/schema',
    vramEstimate: 'settings/vram-estimate',
    export: 'settings/export',
    import: 'settings/import',
    validate: 'settings/validate',
  },
  admin: {
    restartServers: 'admin/servers/restart',
    stopServers: 'admin/servers/stop',
    externalServersStatus: 'admin/external-servers/status',
  },
  codeChat: {
    workspaces: 'code-chat/workspaces',
    validateWorkspace: 'code-chat/workspaces/validate',
    contexts: 'code-chat/contexts',
    createContext: 'code-chat/contexts/create',
    refreshContext: (name: string) => `code-chat/contexts/${name}/refresh`,
    presets: 'code-chat/presets',
    preset: (name: string) => `code-chat/presets/${name}`,
    query: 'code-chat/query',
    cancel: (sessionId: string) => `code-chat/cancel/${sessionId}`,
  },
  instances: {
    list: 'instances',
    get: (id: string) => `instances/${encodeURIComponent(id)}`,
    create: 'instances',
    update: (id: string) => `instances/${encodeURIComponent(id)}`,
    delete: (id: string) => `instances/${encodeURIComponent(id)}`,
    start: (id: string) => `instances/${encodeURIComponent(id)}/start`,
    stop: (id: string) => `instances/${encodeURIComponent(id)}/stop`,
    status: (id: string) => `instances/${encodeURIComponent(id)}/status`,
    startAll: 'instances/start-all',
    stopAll: 'instances/stop-all',
    presets: 'instances/presets',
  },
} as const;
